/* eslint-disable camelcase */

import { Theme } from "./redux/themeSlice";
import { COLORS } from "./util/appkit";

export const lightMode: Theme = {
  background: COLORS.neutral15,
  menu_background: COLORS.neutral05,
  text: COLORS.neutral90,
  error: '#ed1741',
  element_bg: COLORS.neutral05,
  multiValue: COLORS.neutral15,
  focused: COLORS.neutral20,
  focus_text: COLORS.neutral90,
  selected: COLORS.neutral25,
  disabled: 'rgba(0, 0, 0, 0.55)',
  menuBorder: `1px solid ${COLORS.neutral30}`,
  boxShadow: `0 0 2px 2px ${COLORS.neutral30}`,
  boxShadow_tiles: '0 5px 10px 0px rgba(150, 150, 150, 0.5)',
  singleKey_bg: COLORS.neutral10,
  singleKey_border: COLORS.neutral20,
  invert_wave: 'invert(0%)',
  inverted_text: COLORS.neutral90, // for "Generating waveform" text: in lightMode it's not inverted, so it has to be black
  tooltip: COLORS.neutral80,
  tooltip_text: COLORS.neutral05,
  element_outline: '2px solid transparent',
  selected_text: COLORS.neutral90,
  dropdown_border: `1px solid ${COLORS.neutral40}`,
  menuButton_outline: '2px solid transparent',
  button_outline: 'none',
  button_color: COLORS.neutral10,
  indicator_color: COLORS.neutral60,
  icon_color: COLORS.neutral05,
  background_finish_menu_icon: COLORS.neutral15,
  background_play_icon: COLORS.neutral60,
  background_preview_icon: COLORS.neutral60,
  waveform_filter: 'invert(44%) sepia(8%) saturate(3893%) hue-rotate(169deg) brightness(99%) contrast(90%)', // All this just to turn the black part of the waveform image blue. Generated with: https://isotropic.co/tool/hex-color-to-css-filter/
  waveform_bg: '',
  scrubber: COLORS.neutral60,
  scrubber_handle: COLORS.neutral05,
  subtitle_segment_bg: 'rgba(0, 0, 0, 0.4)',
  subtitle_segment_border: `1px solid ${COLORS.neutral80}`,
  subtitle_segment_text: COLORS.neutral05,
  header_bg: COLORS.neutral80,
  metadata_highlight: COLORS.neutral50,
  clock_bg: COLORS.neutral15,
  clock_border: '2px solid transparent',
  clock_hands: COLORS.neutral50,
  clock_focus: COLORS.neutral90,
  digit_selected: COLORS.neutral90,
  text_shadow: `2px 0 ${COLORS.neutral15}, -2px 0 ${COLORS.neutral15}, 0 2px ${COLORS.neutral15}, 0 -2px ${COLORS.neutral15},` +
               `1px 1px ${COLORS.neutral15}, -1px -1px ${COLORS.neutral15}, 1px -1px ${COLORS.neutral15}, -1px 1px ${COLORS.neutral15}`,
};

export const darkMode: Theme = {
  background: COLORS.neutral15,
  menu_background: COLORS.neutral05,
  text: COLORS.neutral90,
  error: 'rgba(237, 23, 65, 0.8)',
  element_bg: COLORS.neutral05,
  multiValue: COLORS.neutral15,
  focused: COLORS.neutral20,
  focus_text: COLORS.neutral90,
  selected: COLORS.neutral25,
  disabled: 'rgba(255, 255, 255, 0.5)',
  menuBorder: `1px solid ${COLORS.neutral30}`,
  boxShadow: `0 0 5px ${COLORS.neutral30}`,
  boxShadow_tiles: '0 5px 10px 0px rgba(100, 100, 100, 0.3)',
  singleKey_bg: 'linear-gradient(180deg, rgba(40,40,40,1) 0%, rgba(30,30,30,1) 100%)',
  singleKey_border: COLORS.neutral20,
  invert_wave: 'invert(100%)',
  inverted_text: COLORS.neutral90,
  tooltip: COLORS.neutral80,
  tooltip_text: COLORS.neutral05,
  element_outline: '2px solid transparent',
  selected_text: COLORS.neutral90,
  dropdown_border: `1px solid ${COLORS.neutral40}`,
  menuButton_outline: '2px solid transparent',
  button_outline: '0px solid transparent',
  button_color: COLORS.neutral10,
  indicator_color: COLORS.neutral60,
  icon_color: 'rgba(255, 255, 255, 0.87)',
  background_finish_menu_icon: COLORS.neutral15,
  background_play_icon: COLORS.neutral60,
  background_preview_icon: COLORS.neutral60,
  waveform_filter: 'invert(11%)',
  waveform_bg: '#fff',
  scrubber: COLORS.neutral60,
  scrubber_handle: COLORS.neutral05,
  subtitle_segment_bg: 'rgba(0, 0, 0, 0.4)',
  subtitle_segment_border: `1px solid ${COLORS.neutral80}`,
  subtitle_segment_text: COLORS.neutral90,
  header_bg: COLORS.neutral30,
  metadata_highlight: COLORS.neutral50,
  clock_bg: COLORS.neutral15,
  clock_border: '2px solid transparent',
  clock_hands: COLORS.neutral50,
  clock_focus: COLORS.neutral90,
  digit_selected: COLORS.neutral90,
  text_shadow: `2px 0 ${COLORS.neutral15}, -2px 0 ${COLORS.neutral15}, 0 2px ${COLORS.neutral15}, 0 -2px ${COLORS.neutral15},` +
               `1px 1px ${COLORS.neutral15}, -1px -1px ${COLORS.neutral15}, 1px -1px ${COLORS.neutral15}, -1px 1px ${COLORS.neutral15}`,
};

export const highContrastDarkMode: Theme = {
  background: '#000',
  menu_background: '#000',
  text: '#fff',
  error: '#ED1741',
  element_bg: 'none',
  multiValue: '#c4c4c4',
  focused: '#a6ffea',
  focus_text: '#000',
  selected: '#fff',
  disabled: 'rgba(255, 255, 255, 0.6)',
  menuBorder: '2px solid #fff',
  boxShadow: '0 0 0 rgba(255, 255, 255, 0.3)',
  boxShadow_tiles: '0 0 0 rgba(255, 255, 255, 0.3)',
  singleKey_bg: 'none',
  singleKey_border: '#fff',
  invert_wave: 'invert(100%)',
  inverted_text: '#000',
  tooltip: '#fff',
  tooltip_text: '#000',
  element_outline: '2px solid #fff',
  selected_text: '#000',
  dropdown_border: '2px solid #fff',
  menuButton_outline: '2px solid transparent',
  button_outline: '2px solid #a6ffea',
  button_color: '#a6ffea',
  indicator_color: '#a6ffea',
  icon_color: '#000',
  background_finish_menu_icon: '#000',
  background_play_icon: '#fff',
  background_preview_icon: '#fff',
  waveform_filter: 'invert(100%)',
  waveform_bg: '#80B8AC',
  scrubber: '#fff',
  scrubber_handle: '#fff',
  subtitle_segment_bg: 'none',
  subtitle_segment_border: '2px solid #fff',
  subtitle_segment_text: '#fff',
  header_bg: '#000',
  metadata_highlight: 'rgb(38, 132, 255)',
  clock_bg: '#000',
  clock_border: '2px solid #a6ffea',
  clock_hands: '#fff',
  clock_focus: '#000',
  digit_selected: '#000',
  text_shadow: '2px 0 #000, -2px 0 #000, 0 2px #000, 0 -2px #000,' +
               ' 1px 1px #000, -1px -1px #000, 1px -1px #000, -1px 1px #000',
}

export const highContrastLightMode: Theme = {
  background: 'snow',
  menu_background: 'snow',
  text: '#000',
  error: '#a5102d',
  element_bg: 'none',
  multiValue: '#2e2e2e',
  focused: '#000099',
  focus_text: '#fff',
  selected: '#4646b5',
  disabled: 'rgba(0, 0, 0, 0.6)',
  menuBorder: '2px solid #000',
  boxShadow: '0 0 0 rgba(0, 0, 0, 0.3)',
  boxShadow_tiles: '0 0 0 rgba(0, 0, 0, 0.3)',
  singleKey_bg: 'none',
  singleKey_border: '#000',
  invert_wave: 'invert(0%)',
  inverted_text: '#fff',
  tooltip: '#000',
  tooltip_text: '#fff',
  element_outline: '2px solid #000',
  selected_text: '#fff',
  dropdown_border: '2px solid #000',
  menuButton_outline: '2px solid transparent',
  button_outline: '3px solid #000099',
  button_color: '#000099',
  indicator_color: '#000099',
  icon_color: '#fff',
  background_finish_menu_icon: 'snow',
  background_play_icon: '#000',
  background_preview_icon: '#000',
  waveform_filter: 'invert(0%)',
  waveform_bg: '#fff',
  scrubber: '#000',
  scrubber_handle: '#000',
  subtitle_segment_bg: 'none',
  subtitle_segment_border: '2px solid #000',
  subtitle_segment_text: '#000',
  header_bg: '#000',
  metadata_highlight: 'rgb(38, 132, 255)',
  clock_bg: 'snow',
  clock_border: '2px solid #000099',
  clock_hands: '#4646b5',
  clock_focus: '#fff',
  digit_selected: '#fff',
  text_shadow: '2px 0 snow, -2px 0 snow, 0 2px snow, 0 -2px snow,' +
               ' 1px 1px snow, -1px -1px snow, 1px -1px snow, -1px 1px snow',
}
