name: Cleanup Deployment

# Removes deployments after a PR was merged or closed.

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  delete-deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        repository: opencast/opencast-editor-test.git
        ref: gh-pages
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        path: editor-test
    
    - name: remove old builds
      run: rm -rf editor-test/${{ github.event.number }}

    - name: regenerate index.html
      run: |
        cd ~/editor-test
        echo '<html><body><ul>' > index.html
        find . -maxdepth 2 -name '*_*' -type d \
          | sort -r \
          | sed 's/^\(.*\)$/<li><a href=\1>\1<\/a><\/li>/' >> index.html
        echo '</ul></body></html>' >> index.html

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_message: Delete old deployments from PR ${{ github.event.number }}
