name: Crowdin » Download translations

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  download-translations:
    if: github.repository_owner == 'opencast'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Prepare git
        run: |
          git config --global user.email 'crowdin-bot@opencast.org'
          git config --global user.name 'Crowdin Bot'

      - name: Prepare crowdin client
        run: |
          wget --quiet https://artifacts.crowdin.com/repo/deb/crowdin3.deb -O crowdin.deb
          sudo dpkg -i crowdin.deb

      - name: Download translations
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          crowdin download --config .crowdin.yaml -b "${GITHUB_REF##*/}"
      # TODO: Find a way to generate only languages that are above a certain threshold
      # - name: Update language list
      #   working-directory: src/i18n/locales
      #   run: $GITHUB_WORKSPACE/.github/generate-lngs.sh > ../lngs-generated.ts

      - name: Add new translations
        run: |
          git add src/i18n/

      - name: Upload translations
        run: |
          if git commit -m "Automatically update translation keys"; then
            git push
          fi
