name: PRs » Publish Pull Request Page

on:
  workflow_run:
    workflows: ["PRs » Build Pull Request Page"]
    types:
      - completed

concurrency:
  group: pull-request-page
  cancel-in-progress: false

jobs:
  deploy-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Prepare git
        run: |
          git config --global user.name "Editor Deployment Bot"
          git config --global user.email "cloud@opencast.org"

      - name: Prepare GitHub SSH key from org level secret
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_TEST }}
        run: |
          install -dm 700 ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Wait for previous workflows to finish
        uses: softprops/turnstyle@v3
        with:
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repository
        run: |
          git clone -b gh-pages "git@github.com:${{ github.repository_owner }}/editor-test.git" editor-test

      - name: Fetch build from GHA
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.workflow_run.id }}-build
          path: ${{ runner.temp }}/
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Store build in the clone
        run: |
          tar xf ${{ runner.temp }}/build.tar

      - name: Fetch pr number from GHA
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.workflow_run.id }}-number
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read PR Number
        run: |
          echo "PR_NUMBER=$(cat pr_number.txt)" >> $GITHUB_ENV

      - name: Store build in the clone
        run: |
          tar xf ${{ runner.temp }}/build.tar

      - name: Cleanup test repository
        working-directory: editor-test
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          wget https://raw.githubusercontent.com/${{ github.repository_owner }}/editor-test/main/.github/scripts/cleanup-deployments.sh
          bash cleanup-deployments.sh ${{ github.repository_owner }}/editor
          rm -f cleanup-deployments.sh
          git add .

      - name: Generate index.html
        working-directory: editor-test
        run: |
          echo '<html><body><ul>' > index.html
          find . -maxdepth 2 -name '*_*' -type d \
            | sort -r \
            | sed 's/^\(.*\)$/<li><a href=\1>\1<\/a><\/li>/' >> index.html
          echo '</ul></body></html>' >> index.html

      - name: Commit new version
        working-directory: editor-test
        run: |
          git add .
          git commit --amend -m "Build ${{ steps.build-path.outputs.build }}"

      - name: Push updates
        working-directory: editor-test
        run: |
          git push origin gh-pages --force

      - name: Add comment with deployment location
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ env.PR_NUMBER }}
          comment-tag: static-test-deployment
          message: >
            This pull request is deployed at
            [test.editor.opencast.org/${{ steps.build-path.outputs.build }}
            ](https://test.editor.opencast.org/${{ steps.build-path.outputs.build }}).

            It might take a few minutes for it to become available.
