name: Build » Playwright UI-Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - develop
      - r/*

env:
  NODE_VERSION: 24

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v7

    - name: Install Node Dependency
      uses: actions/setup-node@v6
      with:
          node-version: ${{ env.NODE_VERSION }}

    - name: Ensure our node version matches the main repo's version for pull requests
      if: github.event_name == 'pull_request'
      run: |
        curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.base_ref }}/pom.xml -o pom.xml
        export FOUND_VERSION="$(grep node.version pom.xml | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)"
        [[ "$FOUND_VERSION" == "$NODE_VERSION" ]] \
        && exit 0 \
        || (echo "Node version does not match.  Expected $NODE_VERSION, found $FOUND_VERSION"; exit 1)
    - name: Ensure our node version matches the main repo's version for push events
      if: github.event_name == 'push' && (startsWith('r/', github.ref_name) || 'develop' == github.ref_name)
      run: |
        curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.ref_name }}/pom.xml -o pom.xml
        export FOUND_VERSION="$(grep node.version pom.xml | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)"
        [[ "$FOUND_VERSION" == "$NODE_VERSION" ]] \
        && exit 0 \
        || (echo "Node version does not match.  Expected $NODE_VERSION, found $FOUND_VERSION"; exit 1)

    - name: Install dependencies
      run: npm ci

    - name: Install supported browsers
      run: npx playwright install

    - name: Prepare configuration
      run: >
        sed -i
        's_https://develop.opencast.org_http://localhost:5173_'
        public/editor-settings.toml

    - name: Prepare mock files
      run: cp -r .github/mock/editor public/

    - name: Build editor
      run: |
        npm run build
        cp public/editor-settings.toml build/

    - name: Use production build for testing
      run: sed -i 's/npm run start/python -m http.server --bind 127.0.0.1 --directory build 5173/' playwright.config.ts

    - name: Run playwright-test
      run: npx playwright test --config=playwright.config.ts

    - name: Upload tests results
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: test-results
        path: test-results/
