name: Build » Vitest tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - develop
      - r/*

env:
  NODE_VERSION: 24

jobs:
  check-npm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Get Node.js
        uses: actions/setup-node@v6
        with:
           node-version: ${{ env.NODE_VERSION }}

      - name: Ensure our node version matches the main repo's version for pull requests
        if: github.event_name == 'pull_request'
        run: |
          curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.base_ref }}/pom.xml -o pom.xml
          export FOUND_VERSION="$(grep node.version pom.xml | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)"
          [[ "$FOUND_VERSION" == "$NODE_VERSION" ]] \
          && exit 0 \
          || (echo "Node version does not match.  Expected $NODE_VERSION, found $FOUND_VERSION"; exit 1)
      - name: Ensure our node version matches the main repo's version for push events
        if: github.event_name == 'push' && (startsWith('r/', github.ref_name) || 'develop' == github.ref_name)
        run: |
          curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.ref_name }}/pom.xml -o pom.xml
          export FOUND_VERSION="$(grep node.version pom.xml | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)"
          [[ "$FOUND_VERSION" == "$NODE_VERSION" ]] \
          && exit 0 \
          || (echo "Node version does not match.  Expected $NODE_VERSION, found $FOUND_VERSION"; exit 1)

      - name: Run npm ci
        run: npm ci

      - name: Execute Vitest tests
        run: npm run test
